import json

with open('nostalgia_data.json','r',encoding='utf-8') as f:
    data = json.load(f)

new_items = [
  {"id":16,"category_id":6,"category":"계절 나기","topic":"연탄난로와 스마트 에어컨","past_desc":"겨울이면 연탄난로 하나가 온 가족의 난방을 책임졌습니다. 연탄 갈 때 피어오르는 연기와 함께 온 식구가 오들오들 떨며 기다리던 그 시절.","present_desc":"이제는 스마트 에어컨이 외출 중에도 앱으로 작동됩니다. 집에 도착하기 전부터 온도를 맞춰두는 것이 일상이 됐습니다.","past_img_prompt":"cute 2D flat vector illustration, warm pastel tone, thick outline, Korean family huddled around round coal briquette stove in winter, grandmother changing coal briquette with tongs, red cheeks, cozy small room with paper doors, 1970s Korea, warm orange and amber tones, no text in image","present_img_prompt":"cute 2D flat vector illustration, warm pastel tone, thick outline, Korean person controlling smart air conditioner on smartphone while riding subway, app showing home temperature, modern apartment interior visible on screen, cool blues and whites, no text in image","comparison_text":"연탄 한 장으로 온 가족이 따뜻했던 그 겨울밤, 추웠지만 서로의 온기로 더 따뜻했습니다."},
  {"id":17,"category_id":6,"category":"계절 나기","topic":"죽부인과 온수매트","past_desc":"여름밤 대나무로 엮은 죽부인을 껴안고 자던 시절. 에어컨도 선풍기도 귀하던 때, 대나무의 서늘한 기운이 유일한 피서였습니다.","present_desc":"요즘은 온수매트가 계절을 가리지 않습니다. 겨울엔 따뜻하게, 여름엔 쿨링 모드로 앱으로 온도를 조절하며 숙면을 취합니다.","past_img_prompt":"cute 2D flat vector illustration, warm pastel tone, thick outline, elderly Korean man sleeping on bamboo mat on wooden floor hugging bamboo body pillow jukbuin, electric fan nearby, summer night, cool greens and soft moonlight blues, no text in image","present_img_prompt":"cute 2D flat vector illustration, warm pastel tone, thick outline, Korean woman adjusting smart heated mat temperature on smartphone before bed, cozy bedroom with soft lighting, modern bedding, warm soft tones, no text in image","comparison_text":"대나무의 서늘한 감촉으로 버티던 그 여름밤, 지금 생각하면 오히려 낭만이었습니다."},
  {"id":18,"category_id":6,"category":"계절 나기","topic":"부채와 에어컨의 여름","past_desc":"어머니가 손수 부채질해 주시던 여름밤. 동네 어른들이 평상에 모여 부채 하나에 의지해 밤바람을 기다리던 풍경이 그립습니다.","present_desc":"지금은 AI 에어컨이 수면 패턴을 분석해 자동으로 온도를 조절합니다. 사람 체온과 날씨를 감지해 최적 환경을 만들어 줍니다.","past_img_prompt":"cute 2D flat vector illustration, warm pastel tone, thick outline, Korean mother fanning sleeping child with colorful paper fan on hot summer night, open window with moonlight, simple bedroom, soft warm summer colors with gentle blues, no text in image","present_img_prompt":"cute 2D flat vector illustration, warm pastel tone, thick outline, modern AI air conditioner displaying sleep mode with moon icon, person sleeping peacefully, bedroom with smart home display showing temperature graph, cool whites and soft blues, no text in image","comparison_text":"어머니의 부채질 한 번이 그 어떤 에어컨보다 더 시원하고 따뜻했습니다."},
  {"id":19,"category_id":7,"category":"골목길 풍경","topic":"평상과 카페 테라스","past_desc":"여름 저녁이면 골목 평상에 온 동네 어른들이 모였습니다. 부침개에 막걸리 한 사발, 수박 한 조각으로 담장 너머 이야기꽃이 피었습니다.","present_desc":"지금은 골목마다 감성 카페 테라스가 들어섰습니다. 인스타용 사진을 찍으며 아메리카노를 마시는 풍경이 새로운 골목 문화입니다.","past_img_prompt":"cute 2D flat vector illustration, warm pastel tone, thick outline, Korean neighborhood elders gathered on wooden bench platform in summer alley evening, watermelon and makgeolli, fireflies, warm lamplight, cozy 1970s neighborhood, earthy warm tones, no text in image","present_img_prompt":"cute 2D flat vector illustration, warm pastel tone, thick outline, young Korean couple at trendy cafe outdoor terrace, brick wall with fairy lights, coffee drinks and cake, taking smartphone photos, warm evening light, pastel greens and pinks, no text in image","comparison_text":"평상 위 수박 한 조각 나누던 그 정겨운 골목, 지금은 사진 속에서만 볼 수 있습니다."},
  {"id":20,"category_id":7,"category":"골목길 풍경","topic":"구멍가게와 무인 편의점","past_desc":"동네 어귀 구멍가게 아저씨는 외상도 해주고 사탕도 한 알 더 얹어주던 이웃이었습니다. 가게 앞 나무 의자에 앉아 참외 먹던 기억.","present_desc":"이제는 24시간 무인 편의점 시대. QR코드 하나로 들어가 셀프 계산하고 나옵니다. 편리하지만 눈 맞출 사람 하나 없습니다.","past_img_prompt":"cute 2D flat vector illustration, warm pastel tone, thick outline, friendly Korean corner store owner handing candy to child, small shop filled with goods and snacks, wooden sign, elderly couple chatting outside on bench, 1970s neighborhood, warm golden tones, no text in image","present_img_prompt":"cute 2D flat vector illustration, warm pastel tone, thick outline, person scanning QR code to enter unmanned convenience store at night, bright fluorescent interior visible through glass, self-checkout kiosk, empty aisles, cool blues and whites, no text in image","comparison_text":"외상장부 한 칸에 담긴 구멍가게 아저씨의 인심, 그 따뜻함이 그리운 날입니다."},
  {"id":21,"category_id":7,"category":"골목길 풍경","topic":"골목 이발소와 헤어샵","past_desc":"빙글빙글 돌아가는 삼색 봉 아래 동네 이발소. 이발사 아저씨와 나누는 세상 이야기가 면도 서비스만큼 푸짐하던 곳.","present_desc":"지금은 예약 앱으로 스타일리스트를 고르는 시대. 헤어샵마다 SNS 피드처럼 꾸며진 인테리어에 전문 케어 서비스가 가득합니다.","past_img_prompt":"cute 2D flat vector illustration, warm pastel tone, thick outline, Korean barber giving haircut to elderly man in traditional neighborhood barbershop, spinning tricolor pole outside, mirrors and vintage chairs, 1970s street visible through window, warm nostalgic tones, no text in image","present_img_prompt":"cute 2D flat vector illustration, warm pastel tone, thick outline, modern Korean hair salon with stylish interior, hairdresser coloring hair of young woman, plant decorations and neon sign, customers booking via smartphone app, trendy pinks and greens, no text in image","comparison_text":"이발소 의자에 앉아 나누던 소소한 이야기들, 그 시절 이발소는 마을의 사랑방이었습니다."},
  {"id":22,"category_id":8,"category":"학교 생활","topic":"육성회비와 디지털 학교","past_desc":"매달 육성회비 봉투를 들고 학교 가던 아이들. 내지 못하면 교실 앞에 이름이 불리던 그 민망함을 기억하시나요?","present_desc":"이제는 학교 앱에서 모든 납부가 이뤄집니다. 급식비, 현장학습비, 통지표까지 학부모는 스마트폰으로 학교생활 전반을 확인합니다.","past_img_prompt":"cute 2D flat vector illustration, warm pastel tone, thick outline, Korean schoolchildren in 1970s classroom handing white envelopes to teacher at desk, wooden desks, chalkboard, school uniforms, warm yellows and browns, no text in image","present_img_prompt":"cute 2D flat vector illustration, warm pastel tone, thick outline, Korean parent using school management smartphone app, notifications showing lunch menu and activity schedule, child doing homework on tablet at home, bright modern living room, clean blues and greens, no text in image","comparison_text":"육성회비 봉투를 꼭 쥐고 등교하던 그 아침이, 지금 아이들에겐 상상도 못 할 이야기입니다."},
  {"id":23,"category_id":8,"category":"학교 생활","topic":"조개탄 난로와 스마트 교실","past_desc":"겨울 교실 한가운데 조개탄 난로 한 대. 도시락을 난로 위에 올려 데우고, 난로 주변 자리가 최고 명당이었던 그 시절.","present_desc":"이제는 최첨단 스마트 교실. 전자칠판에 태블릿 수업, AI 튜터가 학생 개개인의 수준에 맞춰 맞춤형 학습을 제공합니다.","past_img_prompt":"cute 2D flat vector illustration, warm pastel tone, thick outline, Korean students in winter school uniforms gathering around coal stove in 1970s classroom, lunch boxes warming on stove, frosted windows, snowy outside, warm amber classroom glow, no text in image","present_img_prompt":"cute 2D flat vector illustration, warm pastel tone, thick outline, modern Korean classroom with large smart interactive whiteboard, students using tablets, bright LED lighting, teacher using digital pen, clean modern school design, cool whites and blues, no text in image","comparison_text":"난로 주변에 옹기종기 모여 도시락을 데우던 그 교실, 추웠지만 그 어느 곳보다 따뜻했습니다."},
  {"id":24,"category_id":8,"category":"학교 생활","topic":"운동장 조회와 온라인 학습","past_desc":"매일 아침 운동장 조회. 전교생이 줄 맞춰 서서 교장 선생님 훈화 말씀을 듣던 시간. 여름엔 쓰러지는 아이도 있었지요.","present_desc":"코로나를 거쳐 정착된 온라인 학습. 집에서 화상으로 수업을 듣고, 유튜브 강의와 AI 피드백으로 예습과 복습까지 가능한 시대.","past_img_prompt":"cute 2D flat vector illustration, warm pastel tone, thick outline, Korean elementary school children lined up in rows on playground for morning assembly, teacher on podium with megaphone, sunny morning, school uniforms, 1970s school yard with large tree, warm yellows and greens, no text in image","present_img_prompt":"cute 2D flat vector illustration, warm pastel tone, thick outline, Korean student attending online class on laptop at home desk, teacher visible on screen, notes and textbooks beside laptop, comfortable home study setup, soft warm study room lighting, no text in image","comparison_text":"운동장 조회에서 꼿꼿이 서 있던 그 시절, 불편했지만 함께여서 버틸 수 있었습니다."},
  {"id":25,"category_id":9,"category":"문구와 놀이","topic":"종이 인형과 캐릭터 굿즈","past_desc":"종이 인형에 옷을 갈아입히며 놀던 오후. 가위로 조심조심 옷을 오리고 접어서 입히던 그 집중력과 설렘은 지금의 어떤 게임도 따라오지 못합니다.","present_desc":"이제 아이들은 BTS, 산리오, 포켓몬 캐릭터 굿즈를 모읍니다. 한정판 피규어를 위해 새벽부터 줄을 서는 것이 새로운 놀이 문화입니다.","past_img_prompt":"cute 2D flat vector illustration, warm pastel tone, thick outline, Korean girl carefully cutting paper doll clothes with scissors, colorful paper clothes laid out, simple wooden floor, afternoon sunlight streaming in, 1970s home, warm golden pastels, no text in image","present_img_prompt":"cute 2D flat vector illustration, warm pastel tone, thick outline, Korean children admiring collection of character figurines and goods on shelf, Sanrio and cute character merchandise, colorful display, bright bedroom, pastel pinks and purples, no text in image","comparison_text":"종이 한 장으로도 충분히 행복했던 그 시절, 상상력이 최고의 장난감이었습니다."},
  {"id":26,"category_id":9,"category":"문구와 놀이","topic":"딱지치기와 트레이딩 카드","past_desc":"두꺼운 딱지를 직접 접고 그것으로 상대방 딱지를 뒤집던 그 손맛. 학교 앞 공터에서 해가 지도록 딱지치기에 열중하던 아이들.","present_desc":"지금 아이들의 트레이딩 카드는 수십만 원짜리 포켓몬 카드. 희귀 카드 하나에 어른들도 흥분하며 팩을 뜯는 시대가 되었습니다.","past_img_prompt":"cute 2D flat vector illustration, warm pastel tone, thick outline, Korean boys playing ddakji card flipping game on dirt ground after school, homemade paper cards, dusty school street, competitive expressions, 1970s afternoon, warm earthy tones, no text in image","present_img_prompt":"cute 2D flat vector illustration, warm pastel tone, thick outline, excited child opening Pokemon trading card pack, rare holographic card glowing, collection binder full of cards nearby, bright colorful bedroom, vivid yellows and blues, no text in image","comparison_text":"직접 접은 딱지 하나에 온 마음을 걸었던 그 승부욕, 그때가 가장 순수한 경쟁이었습니다."},
  {"id":27,"category_id":9,"category":"문구와 놀이","topic":"구슬치기와 모바일 게임","past_desc":"땅바닥에 구멍을 파고 구슬을 굴리던 방과 후 풍경. 맞추면 가져가는 단순한 규칙이지만 그 전략과 집중력은 어른들도 감탄할 수준이었습니다.","present_desc":"이제 아이들의 놀이터는 스마트폰 속입니다. 전 세계 친구들과 실시간으로 대전하고, 게임 속 아이템 하나에 용돈을 탈탈 털기도 합니다.","past_img_prompt":"cute 2D flat vector illustration, warm pastel tone, thick outline, Korean boys crouching on ground playing marble game, hole dug in dirt, colorful glass marbles rolling, school bags abandoned nearby, 1970s neighborhood street, warm afternoon light, earthy greens and browns, no text in image","present_img_prompt":"cute 2D flat vector illustration, warm pastel tone, thick outline, Korean child playing mobile game on large tablet, colorful game characters on screen, headphones on, gaming chair, snacks nearby, vibrant game world visible on screen, cool techy blues and purples, no text in image","comparison_text":"구슬 하나에 온 정신을 쏟던 그 집중력, 스마트폰보다 훨씬 고급진 몰입이었습니다."},
  {"id":28,"category_id":10,"category":"운동회와 소풍","topic":"박 터뜨리기와 테마파크","past_desc":"운동회 날 박 터뜨리기의 짜릿함! 눈을 가리고 막대기를 들고 빙빙 돌다 내리쳐 박이 터지면 쏟아지는 사탕에 아이들이 환호하던 그 날.","present_desc":"요즘 아이들은 에버랜드, 롯데월드로 소풍을 갑니다. VR 놀이기구에 포토부스까지 1년 내내 즐길 거리가 넘치는 테마파크 시대.","past_img_prompt":"cute 2D flat vector illustration, warm pastel tone, thick outline, Korean children cheering as a papier-mache ball breaks releasing candy at school sports day, blindfolded child with stick, colorful streamers, 1970s school playground, bright festive colors, no text in image","present_img_prompt":"cute 2D flat vector illustration, warm pastel tone, thick outline, Korean family enjoying theme park, children on colorful rides, themed areas with castle backdrop, everyone smiling with ears headbands, modern amusement park, vivid festive colors, no text in image","comparison_text":"박이 터지며 사탕이 쏟아지던 그 순간의 환호성, 어른이 된 지금도 가슴이 두근거립니다."},
  {"id":29,"category_id":10,"category":"운동회와 소풍","topic":"보물찾기와 키즈카페","past_desc":"소풍날 보물찾기의 설렘. 나무 아래, 돌 틈에 숨겨진 번호표를 찾아 돌아다니다 상품을 타면 그날은 세상에서 가장 행복한 날이었습니다.","present_desc":"요즘 아이들은 실내 키즈카페에서 놉니다. 클라이밍 월, 볼풀, 역할 놀이 공간까지 갖춘 초대형 키즈카페가 새로운 놀이 문화로 자리잡았습니다.","past_img_prompt":"cute 2D flat vector illustration, warm pastel tone, thick outline, Korean children searching excitedly under rocks and behind trees for hidden number tickets at school picnic, spring nature setting, lunch boxes visible, 1970s school outing, bright cheerful spring colors, no text in image","present_img_prompt":"cute 2D flat vector illustration, warm pastel tone, thick outline, children playing in colorful indoor kids cafe with ball pit and climbing wall, parents watching from coffee area, bright primary colors and soft foam structures, modern family space, no text in image","comparison_text":"번호표 하나를 찾던 그 보물찾기의 두근거림, 지금의 키즈카페도 그 설렘만은 못 따라옵니다."},
  {"id":30,"category_id":10,"category":"운동회와 소풍","topic":"도시락 소풍과 체험학습","past_desc":"소풍날 새벽부터 어머니가 싸주신 김밥 도시락. 친구들과 돗자리 펴고 도시락 뚜껑을 여는 순간이 운동회보다 더 기다려졌던 그 날.","present_desc":"이제는 체험학습 일정표가 앱으로 옵니다. 뮤지엄, 과학관, 팜스테이까지 교육과 체험을 결합한 프로그램으로 아이들의 시야를 넓혀줍니다.","past_img_prompt":"cute 2D flat vector illustration, warm pastel tone, thick outline, Korean children opening lunch boxes on picnic mat at school outing, sharing kimbap rolls and fruit, spring flowers and trees, cheerful 1970s school picnic scene, warm spring colors, no text in image","present_img_prompt":"cute 2D flat vector illustration, warm pastel tone, thick outline, Korean students on experiential learning trip at science museum, teacher explaining large exhibit, children using interactive displays, modern museum interior, bright educational colors, no text in image","comparison_text":"어머니 도시락 김밥 한 줄이 세상 어떤 뷔페보다 맛있었던 그 봄날 소풍이 그립습니다."}
]

data['items'].extend(new_items)

with open('nostalgia_data.json','w',encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f'완료. 총 아이템 수: {len(data["items"])}')
